### ISSUE TITLE
Adding this Cocoapod does not give me the updated Code 

### ISSUE THREAD

**Issue by vjujjavarapu-zz** [smahajan28/SMSwipeableTabView#1]
If i add the cocoapod, i did not receive the updated code for the project.
More specifically i got error like SegmentBarAttributes not found. However SegmentAttributes are present. 

I think if you install this from cocoa pods it is giving the code from 12/21/15 . Can you please upload the recent version. I can run this repository however. If i create a new Xcode Project i would not get the current version for jan 5

**Comment by smahajan28** [comment]
I have updated the new version to cocoapods v1.0.0. Closing this issue.
